### ISSUE TITLE
griptape dependency issues

### ISSUE THREAD

**Issue by arianpasquali** [tomsmoker/llm_kg_generator#1]
griptape dependency is not defined. 

Lastest griptape version is not compatible.
I have tested with griptape==0.17.0 and similar releases (from late 2023) and none seems to be compatible neither. 

```
Conflict with pydantic

 27.56 ERROR: Cannot install -r requirements.txt (line 12), griptape and pydantic==2.3.0 because these package versions have conflicting dependencies.
#0 27.56 
#0 27.56 The conflict is caused by:
#0 27.56     The user requested pydantic==2.3.0
#0 27.56     fastapi 0.103.1 depends on pydantic!=1.8, !=1.8.1, !=2.0.0, !=2.0.1, !=2.1.0, <3.0.0 and >=1.7.4
#0 27.56     anthropic 0.3.9 depends on pydantic<2.0.0 and >=1.9.0
```

**Comment by arianpasquali** [comment]
Python dependency show :)

Installing griptape will lead you to trafilatura and lxml issues. 
https://github.com/adbar/trafilatura/issues/532 and https://github.com/adbar/trafilatura/pull/593.

I am investigating it. 

```
lm_kg_generator-backend-1  | Process SpawnProcess-1:
llm_kg_generator-backend-1  | Traceback (most recent call last):
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
llm_kg_generator-backend-1  |     self.run()
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
llm_kg_generator-backend-1  |     self._target(*self._args, **self._kwargs)
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
llm_kg_generator-backend-1  |     target(sockets=sockets)
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 61, in run
llm_kg_generator-backend-1  |     return asyncio.run(self.serve(sockets=sockets))
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
llm_kg_generator-backend-1  |     return loop.run_until_complete(main)
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
llm_kg_generator-backend-1  |     return future.result()
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/server.py", line 68, in serve
llm_kg_generator-backend-1  |     config.load()
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/config.py", line 467, in load
llm_kg_generator-backend-1  |     self.loaded_app = import_from_string(self.app)
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
llm_kg_generator-backend-1  |     module = importlib.import_module(module_str)
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
llm_kg_generator-backend-1  |     return _bootstrap._gcd_import(name[level:], package, level)
llm_kg_generator-backend-1  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
llm_kg_generator-backend-1  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
llm_kg_generator-backend-1  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
llm_kg_generator-backend-1  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
llm_kg_generator-backend-1  |   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
llm_kg_generator-backend-1  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
llm_kg_generator-backend-1  |   File "/app/app/api.py", line 9, in <module>
llm_kg_generator-backend-1  |     from .llm_response import get_paper_summary, get_paper_update, make_kg, make_cypher_update, graph_response
llm_kg_generator-backend-1  |   File "/app/app/llm_response.py", line 9, in <module>
llm_kg_generator-backend-1  |     from griptape.structures import Workflow
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/griptape/structures/__init__.py", line 2, in <module>
llm_kg_generator-backend-1  |     from griptape.structures.agent import Agent
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/griptape/structures/agent.py", line 4, in <module>
llm_kg_generator-backend-1  |     from griptape.tools import BaseTool
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/griptape/tools/__init__.py", line 4, in <module>
llm_kg_generator-backend-1  |     from .web_scraper.tool import WebScraper
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/griptape/tools/web_scraper/tool.py", line 9, in <module>
llm_kg_generator-backend-1  |     from griptape.loaders import TextLoader
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/griptape/loaders/__init__.py", line 4, in <module>
llm_kg_generator-backend-1  |     from .web_loader import WebLoader
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/griptape/loaders/web_loader.py", line 7, in <module>
llm_kg_generator-backend-1  |     import trafilatura
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/trafilatura/__init__.py", line 17, in <module>
llm_kg_generator-backend-1  |     from .core import bare_extraction, baseline, extract, html2txt, process_record
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/trafilatura/core.py", line 15, in <module>
llm_kg_generator-backend-1  |     from .external import (SANITIZED_XPATH, justext_rescue, sanitize_tree,
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/trafilatura/external.py", line 12, in <module>
llm_kg_generator-backend-1  |     from justext.core import (ParagraphMaker, classify_paragraphs, preprocessor,
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/justext/__init__.py", line 12, in <module>
llm_kg_generator-backend-1  |     from .core import justext
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/justext/core.py", line 21, in <module>
llm_kg_generator-backend-1  |     from lxml.html.clean import Cleaner
llm_kg_generator-backend-1  |   File "/usr/local/lib/python3.9/site-packages/lxml/html/clean.py", line 18, in <module>
llm_kg_generator-backend-1  |     raise ImportError(
llm_kg_generator-backend-1  | ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
llm_kg_generator-backend-1  | Install lxml[html_clean] or lxml_html_clean directly.
```

**Comment by arianpasquali** [comment]
This worked

In include this in the dockerfile
RUN pip install lxml_html_clean
RUN pip install trafilatura==1.8.1
RUN pip install lxml==5.1.0
RUN pip install griptape==0.19.0
RUN pip install llama-index==0.8.12
RUN pip install langchain==0.0.290
